<a href="https://colab.research.google.com/github/Ravneet7878/ML-Codes/blob/main/Naive_Bayes_Algorithm_Using_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import CategoricalNB

In [ ]:
golf = pd.read_csv("golf.csv")

In [ ]:
golf

Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
first = LabelEncoder()
golf["Outlook"] = first.fit_transform(golf["Outlook"])

second = LabelEncoder()
golf["Temperature"] = second.fit_transform(golf["Temperature"])

third = LabelEncoder()
golf["Humidity"] = third.fit_transform(golf["Humidity"])

fourth = LabelEncoder()
golf["Windy"] = fourth.fit_transform(golf["Windy"])

fifth = LabelEncoder()
golf["Play"] = fifth.fit_transform(golf["Play"])

In [ ]:
golf

Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      0     0
1         2            1         0      1     0
2         0            1         0      0     1
3         1            2         0      0     1
4         1            0         1      0     1
5         1            0         1      1     0
6         0            0         1      1     1
7         2            2         0      0     0
8         2            0         1      0     1
9         1            2         1      0     1
10        2            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        1            2         0      1     0

In [ ]:
X = golf.iloc[:,: -1]
y = golf.iloc[:, -1]

In [ ]:
X

Outlook  Temperature  Humidity  Windy
0         2            1         0      0
1         2            1         0      1
2         0            1         0      0
3         1            2         0      0
4         1            0         1      0
5         1            0         1      1
6         0            0         1      1
7         2            2         0      0
8         2            0         1      0
9         1            2         1      0
10        2            2         1      1
11        0            2         0      1
12        0            1         1      0
13        1            2         0      1

In [ ]:
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play, dtype: int64

In [ ]:
model = CategoricalNB()

In [ ]:
model.fit(X, y)

CategoricalNB()

In [ ]:
X_test = ["sunny", "hot", "normal", False]

In [ ]:
first.transform(["sunny"])

array([2])

In [ ]:
second.transform(["hot"])

array([1])

In [ ]:
third.transform(["normal"])

array([1])

In [ ]:
fourth.transform([False])

array([0])

In [ ]:
X_test = np.array([[2, 1, 1, 0]])

In [ ]:
model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
model.predict_proba(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


array([[0.33508723, 0.66491277]])